<h1 class="title">Les activités au PLVPB</h1>
<h2 id="title-sports">SPORT</h2>
<div id="sports">
  <div class="">
    <a href="aikido.php" class="sport"><i class="fas fa-fist-raised"></i> Aïkido</a>
    <a href="badminton.php" class="sport"><i class="fas fa-feather"></i> Badminton</a>
    <a href="education-physique.php" class="sport"><i class="fas fa-running"></i> Education physique adulte</a>
    <a href="escalade.php" class="sport"><i class="fas fa-mountain"></i> Escalade</a>
    <a href="futsal.php" class="sport"><i class="fas fa-futbol"></i> Futsal</a>
    <a href="gym.php" class="sport"><i class="fas fa-child"></i> Gym Sportive</a>
  </div>
  <div class="">
    <a href="judo.php" class="sport"><i class="fas fa-fist-raised"></i> Judo / Eveil judo</a>
    <a href="jujitsu.php" class="sport"><i class="fas fa-fist-raised"></i> Jujitsu / Self défense</a>
    <a href="karate.php" class="sport"><i class="fas fa-fist-raised"></i> Karaté</a>
    <a href="marche.php" class="sport"><i class="fas fa-hiking"></i> Marche Nordique</a>
    <a href="natation.php" class="sport"><i class="fas fa-swimmer"></i> Natation / Gym aquatique</a>
    <a href="qigong.php" class="sport"><i class="fas fa-spa"></i> Qi gong</a>
  </div>
  <div class="">
    <a href="randonnée.php" class="sport"><i class="fas fa-walking"></i> Randonnée pédestre</a>
    <a href="tennis-de-table.php" class="sport"><i class="fas fa-table-tennis"></i> Tennis de table</a>
    <a href="tir-a-larc.php" class="sport"><i class="fas fa-bullseye"></i> Tir à l'arc</a>
    <a href="velo.php" class="sport"><i class="fas fa-biking"></i> Vélo</a>
    <a href="volley.php" class="sport"><i class="fas fa-volleyball-ball"></i> Volley-ball</a>
    <a href="yoga.php" class="sport"><i class="fas fa-spa"></i> Yoga</a>
  </div>
</div>
<h2 id="title-arts">ART - CULTURE</h2>
<div id="arts">
  <div class="">
    <a href="art-plastique.php" class="art"><i class="fas fa-palette"></i> Arts plastiques</a>
    <a href="ecriture.php" class="art"><i class="fas fa-pen-nib"></i> Atelier écriture</a>
  </div>
  <div class="">
    <a href="photographie.php" class="art"><i class="fas fa-camera"></i> Atelier photographique</a>
    <a href="peinture.php" class="art"><i class="fas fa-paint-brush"></i> Peinture sur porcelaine</a>
  </div>
  <div class="">
    <a href="theatre.php" class="art"><i class="fas fa-theater-masks"></i> Théâtre</a>
    <a href="couture.php" class="art"><i class="fas fa-cut"></i> Couture</a>
  </div>
</div>
<h2 id="title-danses">DANSE</h2>
<div id="danses">
  <div class="">
    <a href="classique.php" class="danse"><i class="fas fa-child"></i> Danse classique</a>
    <a href="hip-hop.php" class="danse"><i class="fas fa-child"></i> Hip-hop</a>
  </div>
  <div class="">
    <a href="modern-jazz.php" class="danse"><i class="fas fa-child"></i> Modern-jazz</a>
    <a href="rock-salsa.php" class="danse"><i class="fas fa-child"></i> Rock / Salsa</a>
  </div>
  <div class="">
    <a href="zumba.php" class="danse"><i class="fas fa-child"></i> Zumba</a>
  </div>
</div>
<h2 id="title-musiques">MUSIQUE - CHANT</h2>
<div id="musiques">
  <div class="">
    <a href="guitare.php" class="musique"><i class="fas fa-guitar"></i> Guitare</a>
    <a href="piano.php" class="musique"><i class="fas fa-music"></i> Piano</a>
  </div>
  <div class="">
    <a href="violon.php" class="musique"><i class="fas fa-music"></i> Violon</a>
    <a href="choeur-enfant.php" class="musique"><i class="fas fa-microphone"></i> Choeur d'enfant</a>
  </div>
  <div class="">
    <a href="chorale-adulte.php" class="musique"><i class="fas fa-microphone-alt"></i> Chorale adulte</a>
  </div>
</div>
