    </div>
    </main>
    <footer>
      <div id = "footer-bar">
        <div class="orange"></div>
        <div class="red"></div>
        <div class="purple"></div>
        <div class="blue"></div>
        <div class="cyan"></div>
        <div class="green"></div>
      </div>
      <span id="partners" href="partner.php">Nos Partenaires</span>
      <div id="partner-carousel">
          <div class="partner-item active">
            <a href="https://www.ufolep.org/"><img src="img/partner/logo-ufolep-lyon.png" alt="logo-ufolep" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://laligue69.org/"><img src="img/partner/logo-fol.png" alt="logo-fol" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://mairie3.lyon.fr/"><img src="img/partner/logo-lyon3.png" alt="logo-lyon3" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.grandlyon.com/"><img src="img/partner/20150930_gl_logo-couleur.jpg" alt="logo-grandlyon" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.auvergnerhonealpes.fr/"><img src="img/partner/logo rgion.jpg" alt="logo-region" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.rhone.fr/"><img src="img/partner/logo-departement-rhone.png" alt="logo-departement" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.lyon.fr/"><img src="img/partner/logo-villedelyon.png" alt="logo-lyon" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.intermarche.com/"><img src="img/partner/logo-intermarche.png" alt="logo-intermarche" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="http://www.bel-encadrement.fr/"><img src="img/partner/logo-bel.png" alt="logo-bel" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="http://www.eiffage.com/"><img src="img/partner/eiffage.jpg" alt="logo-eiffage" class="partner"></a>
          </div>
          <div class="partner-item">
            <a href="https://www.icade.fr/"><img src="img/partner/icade.jpg" alt="logo-icade" class="partner"></a>
          </div>
      </div>

        <nav>
          <a href="https://www.facebook.com/PLVPB/">Facebook</a>
          <a href="boutique.php">Boutique</a>
          <a href="contact.php">Contact</a>
          <a href="gallery.php?page=1">Galerie photo</a>
          <a href="img/PLVPB-190730-Plaquette activite BAT2.pdf">Dépliant 2019-2020</a>
        </nav>

      <span id="PLVPB">Association PLVPB</span>
      <small>© PLVPB - 14 Impasse St Eusèbe, 69003 Lyon - Tél : 04 78 53 19 23 - contact : info@plvpb.com</small>

    </footer>
    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- -->
    <script src="js/jquery.js" charset="utf-8"></script>
    <script src="js/main.js" charset="utf-8"></script>
  </body>
</html>
