<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- CSS -->
  <link rel="stylesheet" href="css/style.css">
  <!-- TinyMCE -->
  <script src="https://cdn.tiny.cloud/1/bjm3zvsk4tnhhwug2f7jor5re6xv8pl6t48i4mb5ryx4sbdw/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
  <script src="js/tinymce.js" charset="utf-8"></script>
  <!-- Font Awesome -->
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-auto-replace-svg="nest"></script>
  <title>PLVPB</title>
</head>
<body>
  <!-- Fb page -->
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v7.0"></script>
  <header>
    <a href='index.php'><img id="logo" src="img/logo.png" alt="logo PLVPB"></a>
    <a id="link-logo" href='index.php'><img id="logo-mobil" src="img/logo-mobil.jpg" alt="logo PLVPB"></a>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: white;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="association" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              L'ASSOCIATION
            </a>
            <div class="dropdown-menu" aria-labelledby="association">
              <a class="dropdown-item" href="#">Qui sommes-nous ?</a>
              <a class="dropdown-item" href="bureau.php">Bureau</a>
              <a class="dropdown-item" href="#">Conseil d'administration</a>
              <a class="dropdown-item" href="#">Mentions légales</a>
              <a class="dropdown-item" href="#">Bénévolat</a>
            </div>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="activites.php">ACTIVITES</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="village-vacances.php">VILLAGE VACANCES</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="evenements.php">EVENEMENTS</a>
          </li>
          <?php if(empty($_SESSION['user'])): ?>
          <li class="nav-item active">
            <a class="nav-link" href="login.php">CONNEXION</a>
          </li>
        <?php else: ?>
          <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="connexion" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?= strtoupper($_SESSION['user']['firstname']); ?>
          </a>
          <div class="dropdown-menu" aria-labelledby="connexion">
            <a class="dropdown-item" href="account.php">Mon compte</a>
            <a class="dropdown-item" href="logout.php">Se déconnecter</a>
          </div>
        </li>

        <?php endif; ?>
        </ul>
      </div>
    </nav>
  </header>
  <main>
    <div class="contain">
