  <div id="carousel">
    <div class="item active">
      <img src="img/carousel/slide1.jpg" alt="img1">
    </div>
    <div class="item">
      <img src="img/carousel/slide2.jpg" alt="img2">
    </div>
    <div class="item">
      <img src="img/carousel/slide3.jpg" alt="img3">
    </div>
    <div class="item">
      <img src="img/carousel/slide4.jpg" alt="img4">
    </div>
    <div class="item">
      <img src="img/carousel/slide5.jpg" alt="img5">
    </div>
    <div class="item">
      <img src="img/carousel/slide6.jpg" alt="img6">
    </div>
    <div class="item">
      <img src="img/carousel/slide7.jpg" alt="img7">
    </div>
    <div class="item">
      <img src="img/carousel/slide8.jpg" alt="img8">
    </div>
    <div class="item">
      <img src="img/carousel/slide9.jpg" alt="img9">
    </div>
    <div class="item">
      <img src="img/carousel/slide10.jpg" alt="img10">
    </div>
    <div class="item">
      <img src="img/carousel/slide11.jpg" alt="img11">
    </div>
    <div class="item">
      <img src="img/carousel/slide12.jpg" alt="img12">
    </div>
    <div class="item">
      <img src="img/carousel/slide13.jpg" alt="img13">
    </div>
    <div class="item">
      <img src="img/carousel/slide14.jpg" alt="img14">
    </div>
    <div class="item">
      <img src="img/carousel/slide15.jpg" alt="img15">
    </div>
    <div class="item">
      <img src="img/carousel/slide16.jpg" alt="img16">
    </div>
    <div class="item">
      <img src="img/carousel/slide17.jpg" alt="img17">
    </div>
    <div class="item">
      <img src="img/carousel/slide18.jpg" alt="img18">
    </div>
    <div class="item">
      <img src="img/carousel/slide19.jpg" alt="img19">
    </div>
    <div class="item">
      <img src="img/carousel/slide20.jpg" alt="img20">
    </div>
    <div class="item">
      <img src="img/carousel/slide21.jpg" alt="img21">
    </div>
    <div class="item">
      <img src="img/carousel/slide22.jpg" alt="img22">
    </div>
  </div>

<section id="acceuil">
  <article class="">
    <h1 class="title">Bienvenu sur le site de l'asssociation PLVPB</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </article>
  <div class="fb-page" data-href="https://www.facebook.com/PLVPB" data-tabs="timeline" data-width="" data-height="" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
    <blockquote cite="https://www.facebook.com/PLVPB" class="fb-xfbml-parse-ignore">
      <a href="https://www.facebook.com/PLVPB">PLVPB</a>
    </blockquote>
  </div>
</section>
