<h1 class='title'>Connexion</h1>
<form class="logs" method="POST" action="login.php">
  <div class="form-group">
    <?php if(!empty($erreur)){
      echo "<p class='erreur'>".$erreur."</p>";
    } ?>
  </div>
  <div class="form-group">
    <label for="mail">Adresse email</label>
    <input type="email" class="form-control" name="mail" aria-describedby="emailHelp">
  </div>
  <div class="form-group">
    <label for="password">Mot de passe</label>
    <input type="password" class="form-control" name="password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" name="check">
    <label class="form-check-label" for="check">Se souvenir de moi</label>
  </div>
  <div class="form-group">
    <a href="register.php">Vous n'avez pas encore de compte ?</a>
  </div>
  <button type="submit" class="btn btn-primary btn-logs">Valider</button>
</form>
