<h1 class='title'>Inscription</h1>
<form class="logs" method="POST" action="register.php">
  <div class="form-group">
    <label for="name">Nom</label>
    <input type="text" class="form-control" name="name">
  </div>
  <div class="form-group">
    <label for="firstname">Prénom</label>
    <input type="text" class="form-control" name="firstname">
  </div>
  <div class="form-group">
    <label for="birthday">Date de naissance</label>
    <input type="date" class="form-control" name="birthday">
  </div>
  <div class="form-group">
    <label for="mail">Adresse mail</label>
    <input type="email" class="form-control" name="mail">
  </div>
  <div class="form-group">
    <label for="password">Mot de passe</label>
    <input type="password" class="form-control" name="password">
    <small class='form-text text-muted'>Le mot de passe doit être composé d'au moins 8 caractères et doit comprendre au moins une majuscule, une minuscule et un chiffre.</small>
  </div>
  <div class="form-group">
    <label for="repeat">Confirmez votre mot de passe</label>
    <input type="password" class="form-control" name="repeat">
  </div>
  <div class="form-group">
    <?php if(!empty($erreur)){
      echo "<p class='erreur'>".$erreur."</p>";
    } ?>
  </div>
  <button type="submit" class="btn btn-primary btn-logs">Valider</button>
</form>
