<h1 class="title">Rosans - Le village vacances</h1>
<img class="img-rosans" src="img/rosans/PLVPB-ROSANS-A5-recto.jpg" alt="rosans1">
<img class="img-rosans" src="img/rosans/PLVPB-ROSANS-A5-verso.jpg" alt="rosans2">
<h2 class="title">Accéder au village</h2>
<iframe id="map-rosans" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2397.438610868696!2d5.469560882507335!3d44.39107369672748!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12caf225927793c5%3A0xb730fce282d6a206!2sRosans%20village%20m%C3%A9di%C3%A9val!5e0!3m2!1sfr!2sfr!4v1591883037695!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
<img class="img-rosans" src="img/rosans/tarifs-rosans.jpg" alt="tarifs">
<img class="img-rosans" src="img/rosans/histoire-rosans.jpg" alt="histoire">
